version: "4.36.0"
name: my_docker_setup

services:
  nginx:
    image: nginx:alpine
    container_name: nginx_container
    ports:
      - "8080:80"
    configs:
      - source: nginx_config
        target: /etc/nginx/nginx.conf
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./html:/usr/share/nginx/html
    annotations:
      com.example.foo: bar
    depends_on:
      - mysql
    networks:
      - app_network

  mysql:
    image: mysql:8.0
    container_name: db_mysql_container
    ports:
      - "3306:3306" 
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: userdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    annotations:
      com.example.foo: bar
    volumes:
      - db_data:/var/lib/mysql 
    networks:
      - app_network
    restart: "no"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    container_name: phpmyadmin_container
    ports:
      - "8081:80"
    environment:
      PMA_HOST: db_mysql_container
      PMA_PORT: 3306
    annotations:
      com.example.foo: bar
    depends_on:
      - mysql
    networks:
      - app_network
    restart: "no"

  db_postgres:
    image: postgres:latest
    container_name: db_postgres_container
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
    annotations:
      com.example.foo: bar
    dns: 8.8.8.8
    volumes:
      - db_postgres_data:/var/lib/postgresql/data
    networks:
      - webnet

  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"
    annotations:
      com.example.foo: bar
    dns: 8.8.8.8
    networks:
      - webnet
    restart: "no"
    cap_add:
      - ALL

  mongodb:
    image: mongo:latest
    container_name: mongo_db_container
    ports:
      - "27017:27017"
    annotations:
      com.example.foo: bar
    dns: 8.8.8.8
    volumes:
      - mongodb_data:/data/db
    networks:
      - webnet
    restart: "no"

  rabbitmq:
    image: rabbitmq:latest
    container_name: rabbit_mq_container
    ports:
      - "5672:5672"
      - "15672:15672"
    annotations:
      com.example.foo: bar
    dns: 8.8.8.8
    networks:
      - webnet
    restart: "no"
    cap_add:
      - ALL

  elasticsearch:
    image: elasticsearch:7.17.0
    container_name: elasticsearch_container
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
      - "9300:9300"
    annotations:
      com.example.foo: bar
    dns: 8.8.8.8
    networks:
      - webnet
    restart: "no"

  neo4j:
    image: neo4j:latest
    container_name: neo4j_container
    environment:
      NEO4J_AUTH: neo4j/neo4jpassword
    ports:
      - "7474:7474"
      - "7687:7687"
    annotations:
      com.example.foo: bar
    dns: 8.8.8.8
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs
    networks:
      - webnet

  mariadb:
    image: mariadb:latest
    container_name: maria_db_container
    annotations:
      com.example.foo: bar
    dns: 8.8.8.8
    ports:
      - "3307:3307"
    volumes:
      - mariadb_data:/var/lib/mysql
    restart: "no"
    cap_add:
      - ALL

  memcached:
    image: memcached:latest
    container_name: memcached_container
    dns_search:
      - dc1.example.com
      - dc2.example.com
    ports:
      - "11211:11211"
    annotations:
      com.example.foo: bar
    networks:
      - app_network
    restart: "no"
    cap_add:
      - ALL

networks:
  webnet:
  app_network:

volumes:
  mongodb_data:
  db_data:
  db_postgres_data:
  neo4j_data:
  neo4j_logs:
  mariadb_data:

configs:
  nginx_config:
    file: ./nginx.conf